#include <stdio.h>
#include <stdlib.h>
#include <time.h>

int main() {
    srand(time(NULL));
    int r = (rand() % 20) + 1;
    switch (r) {
        case 1:
            printf("                                _.---. \n");
            printf("                      |\\---/|  / )   |\n");
            printf("          ------------;     |-/ /     |---\n");
            printf("                      )     ( / ---   \n");
            printf("          ===========(       , ==========\n");
            printf("          ||   _     |      |\n");
            printf("          || o/ )    |      | o\n");
            printf("          || ( (    /       ;\n");
            printf("          ||  \\ `._/       /\n");
            printf("          ||   `._        /|\n");
            printf("          ||      |\\    _/||\n");
            printf("        __||_____.|)  |__||____________\n");
            printf("         ________\\  |  |_________________\n");
            printf("                  \\ \\  `-.\n");
            printf("                   `-`--- \n");
            break;
        case 2:
            printf("               /\\____/\\    __\n");
            printf("             .\'  """"  `,-\'  `--.__\n");
            printf("        __,- :   -  -  ;  ' ::     `-. -.__\n");
            printf("     ,-sssss `._  `\' _,\''     ,\'~~~::`.sssss-.\n");
            printf("    |ssssss ,' ,_`--'_    __,' ::  `  `.ssssss|\n");
            printf("   |sssssss `-._____~ `,,'_______,---_;; ssssss|\n");
            printf("    |ssssssssss     `--'~{__   ____   ,'ssssss|\n");
            printf("     `-ssssssssssssssssss ~~~~~~~~~~~~ ssss.-'\n");
            printf("          `---.sssssssssssssssssssss.---'      \n");
            break;
        case 3:
            printf("          M.                                         .:M\n");
            printf("           MMMM.                                   .:MMMM\n");
            printf("           MMMMMMMM                             .:MMMMMMM\n");
            printf("           :MMHHHMMMMHMM.  .:MMMMMMMMM:.      .:MMHHMHMM:\n");
            printf("            :MMHHIIIHMMMM.:MMHHHHIIIHHMMMM. .:MMHIHIIHHM:\n");
            printf("             MMMHIIIIHHMMMIIHHMHHIIIIIHHMMMMMMHHHIIIIHHM:\n");
            printf("             :MMHIIIIIHMMMMMMMHHIIIIIIHHHMMMMMHHII:::IHM.\n");
            printf("              MH:I:::IHHMMMMMHHII:::IIHHMMMHHHMMM:I:IHMM\n");
            printf("              :MHI:HHIHMMHHIIHII::.::IIHMMHHIHHMMM::HMM:\n");
            printf("               MI::HHMMIIM:IIHII::..::HM:MHHII:::IHHMM:\n");
            printf("               MMMHII::..:::IHMMHHHMHHMMI:::...::IHM:\n");
            printf("               :MHHI::....::::HMMMMMMHHI::.. ..:::HM:\n");
            printf("                :MI:.:MH:.....:HMMMMHHMIHMMHHI:HH.:M\n");
            printf("                M:.I..MHHHHHMMMIHMMMMHMMHHHHHMMH:.:M.\n");
            printf("                M:.H..H  I:HM:MHMHI:IM:I:MM::  MMM:M:\n");
            printf("                :M:HM:.M I:MHMIIMMIIHM I:MM::.:MMI:M.\n");
            printf("                'M::MM:IMH:MMII MMHIMHI :M::IIHMM:MM\n");
            printf("                 MH:HMMHIHMMMMMMHMMIMHIIHHHHIMMHHMM\n");
            printf("                  MI:MMMMHI:::::IMM:MHI:::IMMMMHIM\n");
            printf("                  :IMHIHMMMMMM:MMMMMHHHHMMMHI:M\n");
            printf("                    HI:IMIHMMMM:MMMMMMHHHMI:.:M      .....\n");
            printf("        ............M::..:HMMMMIMHIIHMMMMHII:M:::''''\n");
            printf("            ....:::MHI:.:HMMMMMMMMHHHMHHI::M:::::::''''''\n");
            printf("           ''   ...:MHI:.::MMHHHMHMIHMMMMHH.MI..........\n");
            printf("              ''  ...MHI::.::MHHHHIHHMM:::IHM           '''\n");
            printf("                 '  IMH.::..::HMMHMMMH::..:HM:\n");
            printf("                   :M:.H.IHMIIII::IIMHMMM:H.MH\n");
            printf("                    IMMMH:HI:MMIMI:IHI:HIMIHM:\n");
            printf("                  .MMI:.HIHMIMI:IHIHMMHIHI:MIM.\n");
            printf("                 .MHI:::HHIIIIIHHI:IIII::::M:IM.\n");
            printf("                .MMHII:::IHIII::::::IIIIIIHMHIIM\n");
            printf("                MHHHI::.:IHHII:::.:::IIIIHMHIIHM:\n");
            printf("               MHHHII::..::MII::.. ..:IIIHHHII:IM.\n");
            printf("              .MHHII::....:MHII::.  .:IHHHI::IIHMM.\n");
            printf("              MMHHII::.....:IHMI:. ..:IHII::..:HHMM\n");
            printf("              MHHII:::......:IIHI...:IHI::.....::HM:\n");
            printf("             :MMH:::........ ...::..::....  ...:IHMM\n");
            printf("             IMHIII:::..........     .........::IHMM.\n");
            printf("             :MHIII::::......          .......::IHMM:\n");
            printf("              MHHIII::::...             ......::IHMM:\n");
            printf("              IMHHIII:::...             .....::IIHMM,\n");
            printf("              :MHHIII:::I:::...     ....:::I:::IIHMM\n");
            printf("               MMHHIII::IHI:::...........:::IIH:IHMM\n");
            printf("               :MMHHII:IIHHI::::::.....:::::IH:IHMIM\n");
            printf("                MMMHHII:IIHHI:::::::::::::IHI:IIHM:M.\n");
            printf("                MMMHHIII::IHHII:::::::::IHI:IIIHMM:M:\n");
            printf("                :MMHHHIII::IIIHHII::::IHI..IIIHHM:MHM\n");
            printf("                :MMMHHII:..:::IHHMMHHHHI:IIIIHHMM:MIM\n");
            printf("                .MMMMHHII::.:IHHMM:::IIIIIIHHHMM:MI.M\n");
            printf("              .MMMMHHII::.:IHHMM:::IIIIIIHHHMM:MI.M\n");
            printf("            .MMMMHHMHHII:::IHHMM:::IIIIIHHHHMM:MI.IM.\n");
            printf("           .MMHMMMHHHII::::IHHMM::I&&&IHHHHMM:MMH::IM.\n");
            printf("          .MMHHMHMHHII:::.::IHMM::IIIIHHHMMMM:MMH::IHM\n");
            printf("          :MHIIIHMMHHHII:::IIHMM::IIIHHMMMMM::MMMMHHHMM.\n");
            printf("          MMHI:IIHMMHHHI::::IHMM:IIIIHHHMMMM:MMMHI::IHMM.\n");
            printf("          MMH:::IHMMHHHHI:::IHMM:IIIHHHHMMMM:MMHI:.:IHHMM.\n");
            printf("          :MHI:::IHMHMHHII::IHMM:IIIHHHMMMMM:MHH::.::IHHM:\n");
            printf("          'MHHI::IHMMHMHHII:IHMM:IIHHHHMMMM:MMHI:...:IHHMM.\n");
            printf("           :MHII:IIHMHIHHIIIIHMM:IIHHHHMMMM:MHHI:...:IIHMM:\n");
            printf("           'MHIII:IHHMIHHHIIHHHMM:IHHHMMMMM:MHHI:..::IIHHM:\n");
            printf("            :MHHIIIHHMIIHHHIHHHMM:HHHHMMMMM:MHII::::IIIHHMM\n");
            printf("             MHHIIIIHMMIHHHIIHHMM:HHHHMMMM:MMHHIIHIIIIIHHMM.\n");
            printf("             'MHHIIIHHMIIHHIIIHMM:HHHMMMMH:MHHMHII:IIIHHHMM:\n");
            printf("              'MHHIIIHMMIHHHIHHMM:HHHMMMHH:MMIMMMHHHIIIHHMM:\n");
            printf("               'MHHIIHHMIHHHHHMMM:HHHMMMH:MIMMMMMMMMMMHIHHM:\n");
            printf("                'MHIIIHMMIHHHHHMM:HHHMMMH:IMMMMMHHIHHHMMHHM'\n");
            printf("                 :MHHIIHMIHHHHHMM:HHHMMMM:MMHMMHIHMHI:IHHHM\n");
            printf("                  MHHIIHM:HHHHHMM:HHHMMMM:MMMHIHHIHMM:HHIHM\n");
            printf("                   MHHIHM:IHHHHMM:HHHHMM:MMHMIIHMIMMMHMHIM:\n");
            printf("                   :MHIHMH:HHHHMM:HHHHMM:MMHIIHMIIHHMMHIHM:\n");
            printf("                    MMHHMH:HHHHMM:HHHHMM:MHHIHMMIIIMMMIIHM'\n");
            printf("                    'MMMMH:HHHHMM:HHHMM:MHHHIMMHIIII::IHM:\n");
            printf("                     :MMHM:HHHHMM:HHHMM:MHIHIMMHHIIIIIHM:\n");
            printf("                      MMMM:HHHHMM:HHHHM:MHHMIMMMHHHIHHM:MMMM.\n");
            printf("                      :MMM:IHHHMM:HHHMM:MHHMIIMMMHHMM:MMMMMMM:\n");
            printf("                      :MMM:IHHHM:HHHHMM:MMHHHIHHMMM:MMMMMMMMMM\n");
            printf("                       MHM:IHHHM:HHHMMM:MMHHHHIIIMMIIMMMMMMMMM\n");
            printf("                       MHM:HHHHM:HHHMMM:HMMHHHHHHHHHMMMMMMMMM:\n");
            printf("                    .MI:MM:MHHMM:MHMMHMHHMMMMHHHHHHHMMMMMMMMM'\n");
            printf("                   :IM:MMIM:M:MM:MH:MM:MH:MMMMMHHHHHMMMMMMMM'\n");
            printf("                   :IM:M:IM:M:HM:IMIHM:IMI:MMMMMHHHMMMMMM:'\n");
            printf("                    'M:MHM:HM:MN:HMIHM::M'   '::MMMMMMM:'\n");
            printf("                       'M'HMM'M''M''HM'I'\n");
            break;

        case 4:
            printf("                   /\\             /\\\n");
            printf("                  |`\\\\_,--='=--,_//`|  \n");
            printf("                  \\ .'  :\'. .\':  '. /\n");
            printf("                 ==)  _ :  '  : _  (==\n");
            printf("                   |>/O\\   _   /O\\<|\n");
            printf("                   | \\-'~` _ `~'-/ |\n");
            printf("                  >|`===. \\_/ .===`|<\n");
            printf("        jgs .-'-.   \\===\'  |  \'===/   .-'-.\n");
            printf("     .-----{'. '`}---\\,  .-'-.  ,/---{.'. '}-----.\n");
            printf("     |     `'---'`     `~-===-~`     `'---'`     |\n");
            printf("     |     .-------------------------------.     |\n");
            printf("     |     |                               |     |\n");
            printf("     |     |                               |     |\n");
            printf("     |     |                    .--.       |     |\n");
            printf("     |     |                  .'  o \\__    |     |\n");
            printf("     |     |               _.-'    ,(  `   |     |\n");
            printf("     |     |           _.-'      ,;;|      |     |\n");
            printf("     |     |      _.-=' _,''    ,,;;;\'     |     |\\  \n");
            printf("     |     |  .-'`_.-'``-..,,;;;;:\'        |     |\'\\\n");
            printf("     |     |  `'\'`          `\\`\\           |     |.\'`\\\n");
            printf("     |     |                 /^\\\\\\         |     |'.'`}\n");
            printf("     |     |                               |     } '. }\n");
            printf("     |     |                               |    /.'`./\n");
            printf("     |     '-------------------------------'   /. './\n");
            printf("    _|  _                                     /.`'./\n");
            printf("   (.\\-/.)--------.__________________.-------{.'. {\n");
            printf("    \\6 6/         /                  \\       `\\.'`\\\n");
            printf("(   =\\ /=  ______/....................\\______  \\.'.\\\n");
            printf(" \\   /O\\  |                                  |  }'.'}\n");
            printf("  ) /   \\ | [[[[[[[[[[ ===       ()  ()  ()  | {'.'/\n");
            printf(" (  U   U |                       ________   |  `~`\n");
            printf("  \\(|   |)| [[[[[[[[[[ ===       [________]  |\n");
            printf("   _w___w_:----------------------------------:_______\n");
            printf("  |  []  [][][][] [][][][] [][][][] [][][]  == ===== |\n");
            printf("  |                                                  |\n");
            printf("  |   [][][][][][][][][][][][][][]_ [][][] [][][][]  |\n");
            printf("  |   [_][][][][][][][][][][][][]| |[][][] [][][]||  |\n");
            printf("  |   []  [][][][][][][][][][][][__|       [][][]||  |\n");
            printf("  |   [__] [][][][][][][][][][][___]  []   [][][]||  |\n");
            printf("  |   [_]  [_][_____________][_] [_][][][] [__][]||  |\n");
            printf("  '--------------------------------------------------'\n");
            break;
        case 5:
            printf("        /\\_/\\         _\n");
            printf("       /``   \\       / )\n");
            printf("       |n n   |__   ( (\n");
            printf("      =(Y =.'`   `\\  \\ \\\n");
            printf("       {`''`        \\  ) )\n");
            printf("       {       /    |/ /\n");
            printf("        \\\\   ,(     / /\n");
            printf("        ) ) /-'\\  ,_.'\n");
            printf("       (,(,/ ((,,/\n");
            printf(" |____|____|____|____|____|____|____|____|____|____|____|____|____\n");
            printf(" ____|____|____|____|____|____|____|____|____|____|____|____|____|\n");
            printf(" __|____|____|____|____|___|_         ____|____|____|____|____|__\n");
            printf(" |____|____|____|____|___|    (\\.-./)  _|____|____|____|___|___|_ \n");
            printf("____|____|____|____|____|_  = (^ Y ^) =  _|____|____|____|____|__\n");
            printf("|____|____|____|____|____|___ /`---`\\ __|____|____|____|____|____|\n");
            printf(" __|____|____|____|____|____|_U___|_U|____|____|____|____|____|_  \n");
            printf(" |____|____|____|____|____|____|____|____|____|____|____|____|____\n");
            printf("____|____|____|____|____|____|____|____|____|____|____|____|____|_\n");
            break;
        case 6:
            printf("                                               .--.\n");
            printf("                                               `.  \\\n");
            printf("                                                 \\  \\\n");
            printf("                                                  .  \\\n");
            printf("                                                    :   .\n");
            printf("                                                     |    .\n");
            printf("                                                     |    :\n");
            printf("                                                     |    |\n");
            printf("  ..._  ___                                          |    |\n");
            printf(" `.''.`\'\'\'\'''--..___                             |    |\n");
            printf(" ,-\\  \\             ""-...__         _____________/    |\n");
            printf(" / ` ' \'                    `''''''''''                  .\n");
            printf(" \\                                                      L\n");
            printf(" (>                                                      \\\n");
            printf("/                                                         \\\n");
            printf("\\_    ___..---.                                            L\n");
            printf("  `--'         '.                                           \\\n");
            printf("                 .                                           \\_\n");
            printf("                _/`.                                           `.._\n");
            printf("             .'     -.                                             `.\n");
            printf("            /     __.-Y     /""""""-...___,...--------.._            |\n");
            printf("           /   _.'    |    /                \'.      \\   \'--..._    |\n");
            printf("          /   /      /    /                _,. '    ,/           |   |\n");
            printf("          \\_,'     _.'   /              /''     _,-'            _|   |\n");
            printf("                  '     /               `-----''               /     |\n");
            printf("                  `...-'                                       !_____)\n");
            break;
        case 7:
            printf("        .\n");
            printf("       -.\\_.--._.______.-------.___.---------.___\n");
            printf("       )`.                                       `-._\n");
            printf("      (                                              `---.\n");
            printf("      /o                                                  `.\n");
            printf("     (                                                      \\\n");
            printf("   _.'`.  _                                                  L\n");
            printf("   .\"/| '' ''''._                                            |\n");
            printf("      |          \\             |                             J\n");
            printf("                  \\-._          \\                             L\n");
            printf("                  /   `-.        \\                            J\n");
            printf("                 /      /`-.      )_                           `\n");
            printf("                /    .-\"    `    J  ''''-----.`-._             |\\          \n");
            printf("              .'   .'        L   F            `-. `-.___        \\`.\n");
            printf("           ._/   .\"          )  )                `-    .\"""""`.  \\)\n");
            printf("__________((  _.'_       .-'  J              _.-'   .'        `. \\\n");
            printf("                   '''''''((  .\"--.__________(   _.-\"___________)..|----------------._____\n");
            printf("                            ''                '''               ``U\"\n");
            printf("\n");
            printf("-----._______\n");
            printf("             `-------.__________.--\n");
            printf("                       `-.                      ______________.---------------------------\n");
            break;
        case 8:
            printf("       ,___  _______  ___,\n");
            printf("         \\ \\`       `/ /\n");
            printf("    _    /  0       0  \\  \n");
            printf("   ( \\  >=      Y      =<\n");
            printf("    ) )  \\__    w    __/\n");
            printf("   ( (    /`+=+=o=+=+`\\\n");
            printf("    \\ \\__/             \\__\n");
            printf("     \\/   )           (   \\ \n");
            printf("     /   /             \\   \\\n");
            printf("     \\  / /           \\ \\  /\n");
            printf(" jgs  \\/ /-._________.-\\ \\/\n");
            printf("     (((_)             (_)))\n");
            break;
        default:
            printf("                        ,/|         _.--''^``-...___.._.,;\n");
            printf("                      /, \\'.     _-'          ,--,,,--'''\n");
            printf("                     { \\    `_-''       '    /}\n");
            printf("                        `;;'             ;   ; ;\n");
            printf("                  ._.--''     ._,,, _..'  .;.'\n");
            printf("                  (,_....----'''     (,..--''\n");
            break;

    }
    return 0;
}